### ISSUE TITLE
Reset query's conditions after it has been run.

### ISSUE THREAD

**Issue by pnomolos** [vlucas/Spot#19]
From the gist I'd shared with you previously, bringing this up as an issue to further some discussion:

``` php
<?php
    foreach ($customer->people->where(array('name' => 'Bob')) as $person) {
        // Something
    }
    // Later on ...
    foreach ($customer->people->where(array('name' => 'John')) as $person) {
        // This won't do what you expect and will probably have no
        // results (unless someone's name is both Bob and John simultaneously)
    }
?>
```

We'd decided on adding `reset` to a query once an iterator is run.  My thoughts were to add it in here:

``` php
public function getIterator()
{
    // Execute query and return result set for iteration
    $result = $this->execute();
    $this->reset();
    return ($result !== false) ? $result : array();
}
```

I'm also wondering what your thoughts on what should be reset are?  The obvious ones are `$conditions`, `$group`, `$having`, and `$search`.  Should it also include `$limit`, `$order`, and `$offset`?

In addition, queries that are based off of relationship finders should reset back to the conditions specified by the relationship, correct?

**Comment by vlucas** [comment]
I think `getIterator` is a good place for the call, so it doesn't get cleared on `count` (so you can count before your foreach, etc. without it resetting). Resetting the relationships is going to be tricky, and will definitely need test coverage, but yes - that will need to be addressed as well.

**Comment by pnomolos** [comment]
OK, what I'm thinking for saving the conditions from the relationship is a `$baseState` or something like that.  I'm thinking that we may end up needing that `save` method anyway as that seems the most correct in terms of how things should operate (the relationship instantiates the `Query` object, calls whatever methods to set the conditions, then calls `save()` to mark that as the base state.  I'm thinking that `save` would do something like the following:

``` php
public function save() {
    foreach (array('conditions', 'search', 'order', 'group', 'having', 'limit', 'offset') as $condition_var) {
        $this->savedState[$condition_var] = $this->$condition_var;
    }
}
```

And a similar statement on `reset` to return things back to the way they were.

**Comment by vlucas** [comment]
Okay - I can agree with you on this. Then the Relation loader can set the base state with this method that it will be reset to. We will need a better name than `save` though. It will lead to confusion about what it's doing (i.e. saving to a database?).

**Comment by pnomolos** [comment]
Good point.  `saveState` or `saveConditions` perhaps?

**Comment by vlucas** [comment]
Maybe something like `snapshot`, and give `reset` the ability to reset everything and clear all saved states as well if something like `$this->reset(true)` is passed in (boolean flag for hard reset).

**Comment by vlucas** [comment]
This feature has been implemented with the latest commit by @pnomolos 
SHA1: 4692af4a50280c62023e14d044d71586a7131021
