### ISSUE TITLE
Test Suite won't run

### ISSUE THREAD

**Issue by elicwhite** [vlucas/Spot#2]
I can't get the test suite to run, when I attempt it, I get this error:

PHP Fatal error:  Call to a member function migrate() on a non-object in G:\Users\Eli\Desktop\GroupMatch\Library\Spot\Tests\Test\CRUD.php on line 13

If I put die(var_dump($mapper)) before the return message, it shows up as NULL. 

function test_spot_mapper() {
    global $mapper;  
    return $mapper;
}

**Comment by vlucas** [comment]
I'm not sure what to say... the tests run for me:
http://cl.ly/G0FP

Use "phpunit tests/AllTests.php" as the command to run the tests.

**Comment by elicwhite** [comment]
Hmm, so it does. I feel like a N00b. I'll have to figure out what was happening on the way I was loading it. If I run it directly it works as you show.

**Comment by vlucas** [comment]
No sweat. The command used to run the tests isn't exactly spelled out in the docs. I probably would have been confused too it it wasn't my own project.
