### ISSUE TITLE
Entity-level validation

### ISSUE THREAD

**Issue by pnomolos** [vlucas/Spot#6]
Right now validation is performed by the mapper during the `save()` call by calling `validate()`.  However, the only way to add additional validation in at the entity level is during the beforeSave hook that's called.  This makes thing slightly unwieldy, because if you want to validate the entity without attempting to save it you need to run that entity beforeSave hook manually as it won't be called during the mapper-level `validate()` call.  I propose that either a check for an entity having a `validate()` level during the mapper `validate()` call, or `beforeValidate()` and `afterValidate()` events be added.

**Comment by vlucas** [comment]
Seems like a good idea to me. I plan on creating a whole new pluggable validation system (similar to what I did with the new type system), so this alone might actually solve what you are looking for. I still agree though that more hooks are needed for some more advanced stuff.

The whole new validation system is on the Roadmap:
https://github.com/vlucas/Spot/wiki/Roadmap
