### ISSUE TITLE
HasManyThrough help

### ISSUE THREAD

**Issue by derfsubterfuge** [vlucas/Spot#9]
What I'm currently trying to do through Spot is go through a linking table to implement a Many:Many relationship.

So I'm basically working with 3 tables with the following schema:

Table1(id);
Table2(id, idTable1, idTable3);
Table3(id);

In this, there is a 1:many relationship for Table1:Table2 and a many:1 relationship for Table2:Table3.

I basically want to do something like:

$table1Entity = ...

foreach($table1Entity->getTable3s as $table3Entity) {
     do stuff...
}

I am unfortunately having trouble determining the syntax for the relations() function to make this happen.  I know it involves the HasManyThrough type, but I cannot figure out the syntax.  Please help.  Thanks!

**Comment by vlucas** [comment]
Here's an example of HasManyThrough:

## Situation

Chat rooms have user presence - a list of users currently in the chat room. I want to get loaded User entity objects for all the users currently in the chat room. This allows me to display a list of users in the chat room in the sidebar when users enter the room.

## Tables

rooms
room_users
users

## Code I want to use

`$room->users` for a collection of all the users in the room

## Code for the Relation (HasManyThrough on `Room` Entity):

```
    public static function relations()
    {
        return array(
            // Active users in current room
            'users' => array(
                'type' => 'HasManyThrough',
                'entity' => 'Module\User\Entity',
                'where' => array('id' => ':throughEntity.user_id'),
                'throughEntity' => 'Module\Room\Users\Entity',
                'throughWhere' => array('room_id' => ':entity.id')
                )
        );
    }
```

## Explanation

The result Entity we want is `Module\User\Entity` where the id equals the `room_user.user_id` column. We get this by going through the `Module\Room\Users\Entity`, using the current loaded room id matching to `room_users.room_id`.

I am using this exact code and scenario in [Kikuchat](http://kikuchat.com). Hope that example helps, and let me know if you have any further questions.

**Comment by derfsubterfuge** [comment]
It makes so much sense now.  Thanks!

**Comment by elicwhite** [comment]
Vance, I can't get the markdown from your post, can you make that into a wiki page? It's one of the things that doesn't currently have any documentation (and you just wrote some!) :)

**Comment by vlucas** [comment]
Good idea. Just made this a wiki page: https://github.com/vlucas/Spot/wiki/HasManyThrough-Relations
